[tool.poetry]
name = "omnidirectional-car"
version = "0.1.0"
description = ""
authors = ["Zappani <lucas.zappani@ufpr.br>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
kivy = "^2.3.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
